### ISSUE TITLE
Separator in the `keywords` argument of setup()

### ISSUE THREAD

**Issue by frougon** [pypa/sampleproject#106]
Hello,

According to [this thread](https://www.mail-archive.com/distutils-sig@python.org/msg28845.html) and [that commit](https://github.com/pypa/packaging.python.org/commit/e2b5a3b9127cb05d50c188df80bd44f65d8d176f), it seems to me that with `setuptools`, the `keywords` argument of `setup()` expects a string containing a comma-separated list; however, the [setup.py example in the PyPA sample project](https://github.com/pypa/sampleproject/blob/master/setup.py) uses a string containing a space-separated list:

```
keywords='sample setuptools development'
```

Am I somehow mistaken? Besides, if comma-separated list is indeed the correct thing to use, it seems to me that it would be desirable to make it so that each item has spaces trimmed on both sides, so as to allow readable values such as `"sample, setuptools, development"`, as opposed to `"sample,setuptools,development"`. However, the [setuptools docs](https://setuptools.readthedocs.io/en/latest/setuptools.html) seem rather vague in this department:

> `keywords`: list-comma
> 
> (...)
> 
> list-comma: dangling list or string of comma-separated values

Thanks!

**Comment by di** [comment]
Yes, [this PR](https://github.com/pypa/packaging.python.org/pull/674) changed the spec, so this repo should be updated as well.

**Comment by SaltyCatFish** [comment]
Based on the source and https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords, it looks like this issue can be closed.

**Comment by frougon** [comment]
I'm afraid not: in _Developer's Guide → Basic Use_ of the link you gave, there is still an example reading

```
keywords="hello world example examples"
```

that contradicts all the rest.

**Comment by pfmoore** [comment]
That would be an issue to raise against the setuptools project, not here.

**Comment by frougon** [comment]
Fair enough. What about my bug report, then? The first message here mentions a [setup.py example from this project](https://github.com/pypa/sampleproject/blob/master/setup.py). This example contains:

```
# Note that this is a string of words separated by whitespace, not a list.
keywords='sample setuptools development',  # Optional
```

whereas [di's comment](https://github.com/pypa/sampleproject/issues/106#issuecomment-560021537) mentions a PR for the PyPA project whose title is “Change `keywords` field to be comma separated.” How is this consistent?

**Comment by di** [comment]
Yes, this repo still needs updated.
