### ISSUE TITLE
Change "Sample" to "Example"

### ISSUE THREAD

**Issue by fm75** [pypa/sampleproject#108]
[Example vs. Sample](http://www.differencebetween.net/language/words-language/difference-between-example-and-sample/)

**Comment by pfmoore** [comment]
-1. I understand the distinction here, but if we made this change, we'd have to chase down a load of external links to the project, text in 3rd party documentation, etc. There's simply too much disruption to justify correcting a relatively subtle distinction.

**Comment by fm75** [comment]
Actually, if you change the name, existing links will be redirected by github to the repo with the new name.

**Comment by di** [comment]
While I appreciate you raising this, I think "sample" is clear enough to most people that a rename is not worth the effort required.

Furthermore, it's not possible to rename a project on PyPI and have the same redirects happen.

Finally, like @pfmoore said, this would require tracking down a lot of links (to the PyPI project as well).

Thanks again for raising this though!
