### ISSUE TITLE
package will be named src

### ISSUE THREAD

**Issue by AdrienHorgnies** [pypa/sampleproject#110]
Hi.

I've tried renaming the source directory name to 'src'. Installing the produced package will install the package in `site-packages/src` and sure enough, importing it requires `import src` rather than `import package_name`.

**Comment by di** [comment]
Do you mean that in this repo, you renamed the `src/sample` directory to be `src/src`? If so that would be the expected behavior, since `setup.py` uses `packages=find_packages(where='src')` to find packages in the `src` directory.

**Comment by AdrienHorgnies** [comment]
My bad. I renamed the directory in my own project 'src'. As it's what's showed inside this sample project.

```
root/
root/setup.py
root/src
```
But doing that, my package will be named `src`.
Using it requires `import src`, which is not intended.
So to have the expected behaviour, I had to renamed the directory `src` to `projectName`.

**Comment by AdrienHorgnies** [comment]
Now that I watch better, I see that there are two levels of directory, it's `src/sample`. I'll give it a try and close this issue if that was that.

**Comment by pradyunsg** [comment]
Thanks @AdrienHorgnies for filing this issue! Let us know if you tried that out and still have queries. ^>^

I'm going to go ahead and close this due to a lack of response/activity here.

**Comment by AdrienHorgnies** [comment]
Indeed, forgot to come back here, sorry about that.I don't even remember the issue anymore.
