### ISSUE TITLE
Can this project be considered as the official or the standard form for create python packages?

### ISSUE THREAD

**Issue by oscarmcm** [pypa/sampleproject#113]
it's more a question than a real issue, I know there are some alternatives based on [cookiecutter](https://github.com/audreyr/cookiecutter-pypackage#similar-cookiecutter-templates) for example, but can this be taked as a good starting point, or only serves as a reference for the Python Packaging Tutorial.

Thanks.

**Comment by SaltyCatFish** [comment]
@oscarmcm IMHO, this is my starting point for all python projects.  It is bare bones and generic, but excellent for following current best practices without adding packages based on opinion.  It is well documented.  I have a fork that I update that has some my personal workflow built in (ie, Black, pytest, pytest-cov, etc.)

Can this issue be closed?

**Comment by EliuX** [comment]
Is it a better standard to start the project with `src` instead of the name of the project in lowercase?
If I want to import a module, does referencing `src` as a package make sense?

**Comment by rlongio** [comment]
@EliuX In regards to this project, yes.  If you look in the setup.py, you will see it specifies src as the top directory for packages, src not included.  IE if you have src/a/b, you would import 'from a import something' or 'from a.b import something".

**Comment by dmtucker** [comment]
@EliuX You might be interested in https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure

`src` is not a package name. It's just there to take the modules/packages you're packaging out of `.`

**Comment by jeanas** [comment]
Closing as resolved. Yes, this is an official, standard template to create Python package, since it is proposed by the PyPA, which is as “official” as you'll get in Python packaging.
