### ISSUE TITLE
Universal wheels mentioned in docs, but this project does not use them

### ISSUE THREAD

**Issue by bsolomon1124** [pypa/sampleproject#117]
From https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels:

> You can also permanently set the `--universal` flag in setup.cfg (e.g., see sampleproject/setup.cfg)

This project's setup.cfg no longer specifies `--universal` given dropped support for EOL py2.

Should the PyPA docs be changed?

**Comment by pfmoore** [comment]
Are you looking at an out of date copy of that page? I don't see the text you mention there.

**Comment by pradyunsg** [comment]
I don't think the documentation should be changed *now*, but come 2021, I think we should drop that section.

@pfmoore it's the text above the second code box in the "Universal wheels" section.

**Comment by pfmoore** [comment]
Ah, got it now. I think the OP updated the link - thanks!

I think the docs could be changed any time. Python 2 is no longer supported, 2021 is only when *pip* stops supporting it.

**Comment by pradyunsg** [comment]
That works for me. I'm the last person who wants to be "keeping Python 2 alive". :P
