### ISSUE TITLE
request for fresh release

### ISSUE THREAD

**Issue by brainwane** [pypa/sampleproject#122]
Please help me unblock https://github.com/pypa/warehouse/pull/8011 by making and publishing a fresh release of `sampleproject`.

This would be (the first [since November](https://pypi.org/project/sampleproject/#history)), so somewhat user-visible changes include:
* Switch to `src/` layout #104 
* Implement PEP 518 and opt into PEP 517 builds #101
* Drop support for EOL Python 2 #116 
* Update sample author email #118 
* Added python logo image to README.md inline #119 

Somewhat less user-visible changes:
*  Pass positional arguments to pytest #107 
*  Use tox-travis to simplify configuration #99 
*  Update check-manifest invocation #114 
*  Improve tests #121

**Comment by di** [comment]
Released in https://pypi.org/project/sampleproject/2.0.0/

**Comment by brainwane** [comment]
Thank you!
