### ISSUE TITLE
The unit test cannot be run separately

### ISSUE THREAD

**Issue by visuve** [pypa/sampleproject#129]
Steps:
1) ``git clone https://github.com/pypa/sampleproject.git``
2) ``cd sampleproject``
3) ``python3 tests/test_simple.py`` or ``python -m unittest tests/test_simple.py``
4) Output:
```
Traceback (most recent call last):
  File "tests/test_simple.py", line 7, in <module>
    from sample.simple import add_one
ModuleNotFoundError: No module named 'sample'
```
How am I supposed to run the tests classes individually?

**Comment by pradyunsg** [comment]
The tests can only be run after installing the package - this is a best practice, to ensure that the tests are being run against what would be installed for end users vs what's available in your local directory.

**Comment by visuve** [comment]
Yes, but while developing a project with a structure like this, how am I supposed to run the tests? This is a sample project and I think it should have notes on how to develop such.

**Comment by pfmoore** [comment]
You can use an editable install.

The documentation that describes how to build a project starting from something like this sample is at https://packaging.python.org - if that doesn't contain the information you need, you could raise a PR there.

**Comment by visuve** [comment]
Hi @pfmoore is this what you mean with editable: https://packaging.python.org/guides/distributing-packages-using-setuptools/#working-in-development-mode ?

**Comment by pfmoore** [comment]
Yes

**Comment by visuve** [comment]
Ok, thanks. I wish this stuff was mentioned in the readme at least in some detail. Will close this now.

**Comment by michelececcacci** [comment]
I am getting the same error, but for some reasons python 3.10 works. Does anyone have answers on what could cause this?
