### ISSUE TITLE
Can you add examples of multiple entry points/commands?

### ISSUE THREAD

**Issue by marcelourbanolima** [pypa/sampleproject#131]
Could you add to this sample where some entry points/commands/CLI would be in the structure?

This is something that I don't know where to put, for example, you have your code as a library but you want to distribute it with some CLI that use that library. Where would it be stored, in a /bin directory?

What if I also want to add tests to those CLI? Would them be in /bin/test? How the imports would work?

Is it possible to configure the setup.py so when you install the sampleproject its /bin files are accessible like regular commands of the operating system (without requiring to add something extra to $PATH)? 

If you could add that CLI part to this sample I would appreciate a lot.

Thank you

**Comment by dmtucker** [comment]
> Could you add to this sample where some entry points/commands/CLI would be in the structure?

This project has a `sample` CLI command (i.e. defined on the left side of the `=`):
https://github.com/pypa/sampleproject/blob/52966defd6a61e97295b0bb82cd3474ac3e11c7a/setup.py#L174-L185

It calls into `sample.main`:
https://github.com/pypa/sampleproject/blob/52966defd6a61e97295b0bb82cd3474ac3e11c7a/src/sample/__init__.py#L1

Related: https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html

> Where would it be stored, in a /bin directory?

Python decides that based on `sysconfig.get_path("scripts")`.

> What if I also want to add tests to those CLI? Would them be in /bin/test?

IME, they go with all your other tests in `tests/`.

> How the imports would work?

The package is installed in the test environment by `tox`, and imports work normally. There's nothing special about them.
That said, some CLI frameworks offer testing help (e.g. [Click](https://click.palletsprojects.com/en/7.x/testing/)).

> Is it possible to configure the setup.py so when you install the sampleproject its /bin files are accessible like regular commands of the operating system (without requiring to add something extra to $PATH)?

You might be interested in `pipx`: https://pipxproject.github.io/pipx/
Related: https://packaging.python.org/guides/installing-stand-alone-command-line-tools/

**Comment by marcelourbanolima** [comment]
Thanks a lot for your answer and the references. I will study that and I think I will learn a lot.
Thanks for pointing the direction.
