### ISSUE TITLE
No module named 'candlestick.patterns'

### ISSUE THREAD

**Issue by P-Rainbow** [pypa/sampleproject#139]
Hi!

Thank you for the good work on this package.

When I am trying to follow the example, it pops an error.

`from candlestick import candlestick`
`df = candlestick.inverted_hammer(df, target='result')`

Can you please help me with this issue? Thank you.

(Python3.8 in Windows.)

`Traceback (most recent call last):
  File "C:\My Documents\Scripts\WSS 20200323\G.py", line 8, in <module>
    df = candlestick.inverted_hammer(df, target='result')
  File "C:\Python38\lib\site-packages\candlestick\candlestick.py", line 138, in inverted_hammer
    cndl = __create_object('InvertedHammer', target)
  File "C:\Python38\lib\site-packages\candlestick\candlestick.py", line 35, in __create_object
    return __get_class_by_name(class_name)(target=target)
  File "C:\Python38\lib\site-packages\candlestick\candlestick.py", line 27, in __get_class_by_name
    module = __load_module(mod_name)
  File "C:\Python38\lib\site-packages\candlestick\candlestick.py", line 19, in __load_module
    raise e
  File "C:\Python38\lib\site-packages\candlestick\candlestick.py", line 16, in __load_module
    module = __import__(module_path, fromlist=[super_module], level=0)
ModuleNotFoundError: No module named 'candlestick.patterns'
[Finished in 1.8s]`

**Comment by dmtucker** [comment]
```
Traceback (most recent call last):
File "C:\My Documents\Scripts\WSS 20200323\G.py", line 8, in <module>
  df = candlestick.inverted_hammer(df, target='result')
File "C:\Python38\lib\site-packages\candlestick\candlestick.py", line 138, in inverted_hammer
  cndl = __create_object('InvertedHammer', target)
File "C:\Python38\lib\site-packages\candlestick\candlestick.py", line 35, in __create_object
  return __get_class_by_name(class_name)(target=target)
File "C:\Python38\lib\site-packages\candlestick\candlestick.py", line 27, in __get_class_by_name
  module = __load_module(mod_name)
File "C:\Python38\lib\site-packages\candlestick\candlestick.py", line 19, in __load_module
  raise e
File "C:\Python38\lib\site-packages\candlestick\candlestick.py", line 16, in __load_module
  module = __import__(module_path, fromlist=[super_module], level=0)
ModuleNotFoundError: No module named 'candlestick.patterns'
[Finished in 1.8s]
```

Is the `candlestick` code available anywhere? Do you expect `candlestick\patterns.py` to exist?

**Comment by P-Rainbow** [comment]
@dmtucker Thank you for your reply!

Sorry that I missed a line in the earlier post. I am following the sample at [pip](https://pypi.org/project/candlestick-patterns-subodh101/) using below lines, when the error pops:

`from` candlestick import candlestick`
`import pandas as pd`

`df = pd.read_excel("C:\\folder\\3506.xlsx")`
`df = candlestick.inverted_hammer(df, target='result')`

What's the right way to use this package? Thank you.

**Comment by dmtucker** [comment]
No problem :blush: That helps, thanks...

The author of [`candlestick-patterns-subodh101`](https://pypi.org/project/candlestick-patterns-subodh101/) (@subodh101?) should not have this project listed as its homepage :weary:
Probably, they used this project as a template for that package but never changed the project `url`:
https://github.com/pypa/sampleproject/blob/90d44abe361688aba5a189e661423863b34f5208/setup.py#L69-L73

If you ever find you need help and aren't sure where to look, check out [#python on Libera.Chat](https://www.pound-python.org/) or [#python3:matrix.org](https://matrix.to/#/!iuyQXswfjgxQMZGrfQ:matrix.org?via=michaelsasser.org&via=matrix.org&via=kde.org).

Anyways, have you run `pip install candlestick-patterns-subodh101`?
For example,
``` sh
python3 -m venv venv
venv/bin/pip install pandas candlestick-patterns-subodh101
venv/bin/python mymodule.py
```
``` python
# mymodule.py

from candlestick import candlestick
import pandas as pd

df = pd.read_excel("C:\\folder\\3506.xlsx")
df = candlestick.inverted_hammer(df, target='result')
```

**Comment by subodh101** [comment]
Oh no!
Thank you @dmtucker I will fix it :)

**Comment by P-Rainbow** [comment]
@dmtucker , thanks again!

Yes, it's installed in my computer.

![image](https://user-images.githubusercontent.com/43132563/122326479-f1784a80-cf5e-11eb-986e-8178e323c31c.png)

@subodh101 thank you for your attention on the matter. Looking forward to the fix! :)

**Comment by subodh101** [comment]
@dmtucker 
I have updated the url address. You can close this issue now.

@P-Rainbow https://pypi.org/project/candlestick-patterns-subodh101/
If you want to collaborate, kindly email me at subodh.pushkar@gmail.com
I am not sure if it is not a good idea to open source the code because I have not written the base code. But the person who wrote it is not making any updates now. I found it easier to use the code after making a distribution package of it. Thank you for your understanding. 🙇

**Comment by dmtucker** [comment]
> I have updated the url address. You can close this issue now.

Woohoo :tada: Thanks for that... I don't have any special perms here, so @P-Rainbow will have to close.

> I am not sure if it is not a good idea to open source the code

Just be aware that uploading to PyPI makes the source code publicly available:
https://pypi.org/project/candlestick-patterns-subodh101/#files

**Comment by P-Rainbow** [comment]
@subodh101 , superb! I've tried the update and it works! thank you!
@dmtucker , thank you for the help too!
