### ISSUE TITLE
Remove unnecessary items from `MANIFEST.in`

### ISSUE THREAD

**Issue by di** [pypa/sampleproject#152]
Some lines in `MANIFEST.in`, like `include pyproject.toml` are unnecessary with the defaults provided by newer versions of `setuptools`: https://packaging.python.org/guides/using-manifest-in/#how-files-are-included-in-an-sdist

This project should simplify the `MANIFEST.in` file as much as possible, (and update the `pyproject.toml` file to specify a more recent version of `setuptools` as necessary).

**Comment by DiddiLeija** [comment]
Hi @di, I offer to work on this. I'll post a PR as soon as possible.
