### ISSUE TITLE
Make this a template repo

### ISSUE THREAD

**Issue by barakplasma** [pypa/sampleproject#156]
Using the Github Template setting would allow others to copy this repo without forking it, leading to a cleaner git history for their new projects. 
See the docs in https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by pfmoore** [comment]
Personally, I consider this project as a *sample*, not a *template*. It's supposed to contain example code that you can take ideas from, or copy parts of, not a template that you clone and then base your project on. At least that was the original intent. But I'm no longer particularly active on this project, so I'll let the currently active maintainers decide whether usage has changed over time and this project *is* now intended more as a template.

**Comment by di** [comment]
I think in practice, this project is used quite often as a template (see the ~1.5K forks), so making this a GitHub Template would make sense to me.

**Comment by vkhodygo** [comment]
This issue needs more attention. It's clear that most of the forks were created to be integrated into other projects but not to develop this particular one.

**Comment by di** [comment]
Done.
