### ISSUE TITLE
code execution backdoor

### ISSUE THREAD

**Issue by duxinglin1** [pypa/sampleproject#170]
We found a malicious backdoor in versions 1.2.1~1.2.4 of this project, and its malicious backdoor is the request package. Even if the request package was removed by pypi, many mirror sites did not completely delete this package, so it could still be installed.When using pip3 install scm-git -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com, the request malicious plugin can be successfully installed.

![image](https://user-images.githubusercontent.com/58363074/169235585-51e504e0-3d5a-4b4f-9216-5ba935a6d5fa.png)

Repair suggestion: delete version 1.2.1~1.2.4 in PyPI, replace request with requests

**Comment by dmtucker** [comment]
I assume you got here because https://pypi.org/project/scm-git/ never changed the `project_url`.
Looks like they _did_ set the `author_email` though: kevin.j.wang@nokia-sbell.com

**Comment by di** [comment]
This is not the issue tracker for the `scm-git` project.
