### ISSUE TITLE
stock_tokens list returns TypeError: can only concatenate str (not "list") to str

### ISSUE THREAD

**Issue by akhilpakkath** [pypa/sampleproject#173]
if I subscribe to a list of stock_tokens like below
`isec.subscribe_feeds(stock_token=['4.1!35167', '4.1!35168'])`
the `return {"message":"Stock "+stock_token+" subscribed successfully"}`
from `breeze_connect.py` returns `TypeError: can only concatenate str (not "list") to str`
local change to library for all the return lines with a str conversion worked locally
`return {"message":"Stock "+str(stock_token)+" unsubscribed successfully"}`.
Kindly advise if this is the right way

**Comment by akhilpakkath** [comment]
closing

**Comment by akhilpakkath** [comment]
closed accidently

**Comment by akhilpakkath** [comment]
reopening

**Comment by pfmoore** [comment]
Nothing to do with this project. It looks like the isec-connect project has copied this repository but failed to change the contact information. You'll need to find a way to contact that project.
