### ISSUE TITLE
Delay of approx 20 seconds

### ISSUE THREAD

**Issue by Anoop0606** [pypa/sampleproject#174]
Hi Is there an intentional delay added to the responses for the calls . I can see almost 20 seconds delay in all the calls . 

Sample below 

print(com.print_time())
dummy = isec.get_quotes(stock_code='NIFTY',exchange_code="NSE")
print(com.print_time())
print(com.print_time())
dummy = isec.get_quotes(stock_code='NIFTY',exchange_code="NSE")
print(com.print_time())
print(com.print_time())
dummy = isec.get_quotes(stock_code='NIFTY',exchange_code="NSE")
print(com.print_time())

Ouptput ---

21:47:50
21:48:12
21:48:12
21:48:33
21:48:33
21:48:54

**Comment by dmtucker** [comment]
@Anoop0606 what package did you install to get `isec.get_quotes`?

This is just a sample project that package likely used as a template without changing the project URL.
