### ISSUE TITLE
Clarify Python 2 and 3 language

### ISSUE THREAD

**Issue by cjerdonek** [pypa/sampleproject#18]
I think the sample project should be more explicit about its goals with respect to Python 2 and 3, for example in the main README.

Also, [this language](https://github.com/pypa/sampleproject/blob/master/setup.cfg) seems to imply that it's not good practice to write a project targeting only Python 3.

```
[bdist_wheel]
# This flag says that the code is written to work on both Python 2 and Python
#3. If at all possible, it is good practice to do this. If you cannot, you
# will need to generate wheels for each Python version that you support.
universal=1
```

I think that implication should be changed to say that "compatibility with Python 3 is good practice," because writing Python 3-only projects is also good for the community and shouldn't be discouraged.

**Comment by AceAttorneyMaster111** [comment]
How do you generate wheels? Due to the nature of my project, I can only support Python 3.5.

**Comment by pfmoore** [comment]
@cjerdonek I agree, we've moved on from when that was written. How about this?

```python
[bdist_wheel]
# This flag says to generate wheels that support both Python 2 and Python
# 3. If your code will not run unchanged on both Python 2 and 3, you will
# need to generate separate wheels for each Python version that you
# support.
universal=1
```

@AceAttorneyMaster111 Not sure what you mean? `setup.py bdist_wheel` or `pip wheel .` should work. If you don't support Python 2, remove the `universal=1` flag. Your wheel will be compatible with Python 3 only. To restrict it to 3.5 you'll need to set the tag to `py35`, or use metadata to specify the restrictions. That's more advanced usage though, and out of scope for this project.

**Comment by pfmoore** [comment]
https://github.com/pypa/sampleproject/pull/61 created for this

**Comment by pradyunsg** [comment]
Closing since #61 was merged.
