### ISSUE TITLE
How to control spelling incorrection even if phonetically sound same

### ISSUE THREAD

**Issue by akshaysinghal93** [pypa/sampleproject#186]
For eg. For risk(financial usecases) purposes, I want to control the spelling mistakes to some level.
"Ajeeet Singh", "Ajeet Singh" - can be Match
"A Singh", "Ajeet Singh" - can be match
"Ajeit Singh", "Ajeet Singh" - shouldn't be match

**Comment by ross-spencer** [comment]
@akshaysinghal93 this seems like it may be the wrong repository for this issue?
