### ISSUE TITLE
pyproject.toml: references a "python_requires" key that does not exist

### ISSUE THREAD

**Issue by Gadgetoid** [pypa/sampleproject#188]
This line-

https://github.com/pypa/sampleproject/blob/aeeb50a948addcb712ad4261df472263514991e1/pyproject.toml#L89

References a "python_requires" below, which does not appear

This should probably say "requires-python".

**Comment by di** [comment]
Yes, looks like this was missed in #166.

**Comment by chrysle** [comment]
This was fixed in #204.
