### ISSUE TITLE
help! Executing file is not working

### ISSUE THREAD

**Issue by adrianatrevinoe** [pypa/sampleproject#189]
![image](https://user-images.githubusercontent.com/70771428/231056309-9c12d7e9-b2aa-47a2-948e-8280754c8362.png)
Hi! I get the following error when trying to execute it :( 

my toml file looks like this:
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example_package_adrianatrevinoe"
version = "0.0.2"
authors = [
  { name="Adriana Trevino", email="adriana.trevinoe@udem.edu"},
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"

**Comment by dmtucker** [comment]
It looks like you put your toml file in `example_package_adrianatrevinoe/__init__.py` instead of `pyproject.toml`?

**Comment by adrianatrevinoe** [comment]
yes thankyou so much! I don't know why I added a part of the toml file in init, and also i was reinstalling the same version with pip install, i didn't know I had to add ={current_version} at the end! thanks :)
