### ISSUE TITLE
Unclear description of "readme" field in pyproject.toml 

### ISSUE THREAD

**Issue by thomasbbrunner** [pypa/sampleproject#196]
The readme field of the [pyproject.toml](https://github.com/pypa/sampleproject/blob/main/pyproject.toml) contains the following description:

```python
# This is an optional longer description of your project that represents
# the body of text which users will see when they visit PyPI.
#
# Often, this is the same as your README, so you can just read it in from
# that file directly **(as we have already done above)**
# (...)
readme = "README.md" # Optional
```

What exactly does the highlighted part mean ("as we have already done above")? Above where?

Also, if the readme value is set to README.md, does it mean that the file is loaded? If so, could we make it explicit here?

**Comment by thomasbbrunner** [comment]
After a more thorough reading of the pyproject.toml file, apparently the order of the fields in the file was changed but the text was not updated.

I've created a minor PR with updates.

**Comment by chrysle** [comment]
Can this be closed, then?
