### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by 0ldcamel** [pypa/sampleproject#200]
`from tabulate import tabulate
import tabulate_cell_merger.tabulate_cell_merger

table = [['a1', 'b1'], ['a2', 'b2']]
colspan = {(0, 0): 2}
rowspan = {(0, 1): 2}

print(tabulate(table, colspan, rowspan))`

Traceback (most recent call last):
  File "xxx/merge.py", line 11, in <module>
    print(tabulate(table, colspan, rowspan))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.12/site-packages/tabulate/__init__.py", line 2118, in tabulate
    and tablefmt in multiline_formats
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'

**Comment by dmtucker** [comment]
@0ldcamel this is not the right place for that.
Try https://github.com/astanin/python-tabulate

**Comment by 0ldcamel** [comment]
Hello @dmtucker , thank you for your comment. I am new here so I kindly be patient.
I used https://github.com/astanin/python-tabulate and it works fine.

Basically I was trying to merge two cells and tried to use tabulate-cell-merger which is from here: https://pypi.org/project/tabulate-cell-merger/
After a few tries, I went back to the same place [https://pypi.org/project/tabulate-cell-merger/](url). On the left hand side, there are Statistics including Open Issues so I reported the issue there.
I am not sure why should I report the issue at  https://github.com/astanin/python-tabulate because Tabulate works fine. It is Tabulate-cell-merger that doesn't work (at least when I tried).

**Comment by jeanas** [comment]
Indeed, this project is a sample Python projects that Python package authors can use as a starting point, it looks like the author of `tabulate-cell-merger` forgot to update the project URLs. We can't help with your problem, please ask the `tabulate-cell-merger` author if you're still having this problem. Thanks.
