### ISSUE TITLE
Stop advertising adding `wheel` as an unconditional PEP 517 build dependency

### ISSUE THREAD

**Issue by webknjaz** [pypa/sampleproject#203]
It's already pulled in by `setuptools` automatically, when building wheels is requested from the frontend. If only sdists are being build, `pyproject.toml` shouldn't forcefully inject this dependency into the ephemeral build env.

This has mostly been cleaned up from other places in the ecosystem and should be done here as well.

Related PRs:
* https://github.com/pypa/build/pull/716
* https://github.com/pypa/pip/pull/12449
* https://github.com/pypa/setuptools/pull/3056

Action items:
* Find all the `pyproject.toml` files that have `setuptools` in their `[build-system].requires`
* Delete `wheel` from the lists where it's also present

**Comment by pfmoore** [comment]
> Find all the pyproject.toml files that have `setuptools` in their `[build-system].requires`

That sounds more complex than I think you mean - isn't it just the following one line?

https://github.com/pypa/sampleproject/blob/main/pyproject.toml#L153

**Comment by webknjaz** [comment]
You're right. I think there was some other repo under @pypa that has multiple project examples in it that I confused this one with.

**Comment by webknjaz** [comment]
I was thinking of https://github.com/pypa/sample-namespace-packages, it seems.

**Comment by chrysle** [comment]
#204 addresses this.

**Comment by webknjaz** [comment]
@chrysle as I said above — I originally thought of a different repo. Also, that PR does too much stuff than just removing 9 bytes from a single place, which would've been much cleaner.

**Comment by chrysle** [comment]
I guess this can be closed, nevertheless? What's done is done.
