### ISSUE TITLE
Remove Python version 3.7 to unblock tests

### ISSUE THREAD

**Issue by VladimirFokow** [pypa/sampleproject#206]
Currently, Python 3.7 in tests [blocks](https://github.com/pypa/sampleproject/pull/204#issuecomment-1925790953) some tests, so no pull requests are possible. 

- Python v.`3.7` has reached its [end-of-life](https://devguide.python.org/versions/), and v.`3.8` will in 2024. Does this repo have to still support these versions?

- Dropping support for them can ease the burden on maintainers: the deprecated dependencies currently [block](https://github.com/pypa/sampleproject/pull/204#issuecomment-1925780756) the tests for this repo - thus no pull requests are possible.

- Plus, the newer Python versions can be supported here (until `3.12`).

For example, `numpy` [supports](https://numpy.org/news/#numpy-1260-released) only Python 3.9+ [as of 1.26.0 ](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table).

Which Python version should be the min. supported here: `3.8` or `3.9`?

**Comment by pfmoore** [comment]
This repo shouldn't be using anything version-specific as it's intended just as an example. I don't see any objection to updating the Python requirement to 3.8, but I'm -1 on trying to track supported Python versions as that's just ongoing maintenance work (and we don't actually "support" any particular Python versions, so it's not even accurate in any practical sense).
