### ISSUE TITLE
It would be great to add a simple module and a test for that module. 

### ISSUE THREAD

**Issue by jeremyjjbrown** [pypa/sampleproject#26]
This sample project is a very nice thing to finally have. I find most of the documentation of python project structure to be incomplete or opaque.

It would be great to add a very simple module and a test for that module.  Just to see how the imports look.

**Comment by kdbanman** [comment]
+1

**Comment by JakobJakobson** [comment]
+1

**Comment by SaltyCatFish** [comment]
This looks to be the case in the current release; can this issue be closed?

**Comment by di** [comment]
The existing test does not actually test the module.
