### ISSUE TITLE
Bootstrap setuptools

### ISSUE THREAD

**Issue by alexpdp7** [pypa/sampleproject#27]
Hi,

Setuptools recommends bootstraping using ez_setup.py:

http://pythonhosted.org/setuptools/using.html

yet this project does not do so. Given that one might have a valid Python installation which does not have setuptools, perhaps it would be a good idea to bootstrap?

I am not aware of any downsides- if they exist it would be nice if they were clearly documented.

Cheers,

Álex

**Comment by dstufft** [comment]
It's generally recommended *not* to do the ``ez_setup`` bootstrapping anymore.

**Comment by alexpdp7** [comment]
If it's not (which sounds reasonable), could this be pointed out somewhere and a rationale provided? Setuptools still specifies this in its documentation.

Maybe it's somewhere and I've missed it...

**Comment by pfmoore** [comment]
I'd suggest raising an issue/PR with setuptools.

**Comment by alexpdp7** [comment]
I've created:

https://bitbucket.org/pypa/setuptools/issue/336/bootstrap-is-deprecated-remove-from-docs

**Comment by Ivoz** [comment]
Thanks for following up @alexpdp7
