### ISSUE TITLE
add tox.ini and .travis.yml

### ISSUE THREAD

**Issue by qwcode** [pypa/sampleproject#3]
many people use tox and travis, right?

maybe this is "feature creep" for the point of this project, but I don't know.  
I'm inclined to add it.

**Comment by VelizarVESSELINOV** [comment]
:+1: I'm for favorable a complete default project, including all the quality online aspects:
 - CI like Travis, Circle, etc.
 - static code analysis like Quantifiedcode, Codacy, etc.
 - code coverage like Coveralls, Codecov, etc.
 - documentation like Read the Docs, etc.
 - license like MIT, BSD, etc. (#17)

After that how you manage all the possible combinations, if a user want to have a project that is licensed X, CI Y, etc. can be challenging.

One solution is to have several GitHub projects, single project with different branches or build a project template wizard that is creating the project with some user selected options.

**Comment by pfmoore** [comment]
If we include travis, we should probably also include appveyor, to encourage testing cross-platform.

**Comment by gene1wood** [comment]
This was completed in PR #37 . Is this issue clear to be closed?
