### ISSUE TITLE
python setup.py test not working

### ISSUE THREAD

**Issue by guettli** [pypa/sampleproject#33]
The tests of the sampleproject don't get executed:

```
user@host> python setup.py test
running test
```

... nice: all tests pass?

No, since the test (unchanged) looks like this:

```    
    def test_failure(self):
        self.assertTrue(False)
```

I am missing an exception if I run "python setup.py test".

I have no clue how the right way to fix this looks like.

**Comment by pfmoore** [comment]
IMO, this is a setuptools bug. The ```setup.py test``` command is implemented by setuptools, but in this case there are no tests (more precisely, no tests in a place that setuptools expects to find them).

Maybe setuptools should do something to say it ran no tests? I don't know.

We could add instructions on how to run the tests to the project instructions, I guess. But as we don't want to dictate what test runner to use, these would need to be generic "Please put instructions on how to run your tests here". And I'm not sure where those instructions should go. Ironically, I would have put them in ```README.rst```, but as we recently changed to use ```README.rst``` for the long description, that's not really appropriate any more... Suggestions welcome :-)

**Comment by carljm** [comment]
It is common to put such instructions (which are relevant to contributors, but not necessarily to users) in a `CONTRIBUTING.rst` file. As a bonus, GitHub will prominently display a link to this file, if it exists, anytime someone creates a pull request against the project.

**Comment by guettli** [comment]
Since pfmoore said it is an setuptools issue, I create one: https://bitbucket.org/pypa/setuptools/issues/446/setuppy-test-says-it-runs-tests-but-it

**Comment by guettli** [comment]
@carljm it would be nice to a have a default cow-path, so that you don't need to write redundant strings in CONTRIBUTING.rst file for all python packages.

**Comment by carljm** [comment]
@guettli Are you suggesting that sampleproject should have a stock `CONTRIBUTING.rst` in it? That wouldn't bother me at all.

**Comment by guettli** [comment]
No, adding  CONTRIBUTING.rst was not my suggestion. With "redundant strings" I mean this:

If there is **one** common way how to run tests of a package this need to documented this **once**  in the packaging guide.

Since there is not common way yet, there are N document strings explaining how to run tests. Pypi hosts 67k packages. This makes (in theory) 67k times an explanation how to test a package.

I don't care about the wasted bytes. I care about the wasted time to write and read it. It makes me sad. Really, call my crazy, but I have small tear in my eye. Why is there no agreement?

**Comment by guettli** [comment]
In setuptools the issue is accepted and nearly solved. I close this one here.
See  https://bitbucket.org/pypa/setuptools/issues/446/setuppy-test-says-it-runs-tests-but-it
