### ISSUE TITLE
Expand on the testing directory

### ISSUE THREAD

**Issue by pfmoore** [pypa/sampleproject#4]
We should probably flesh out the ```tests``` directory a bit (although it's going to be hard to avoid getting into "my favourite test package" debates...)

* Does the tests directory need ```__init__.py```? (Yes, for some test tools, so probably should be there).
* How are tests run? Will ```setup.py test``` work? Does anyone actually use that? Should we include a (cross-platform) test runner script?
* Do we need a note in ```README.txt``` recommending ```pip install -e``` when running tests, or should the test runner script just set ```sys.path```?

I think we probably should recommend a testing package, specifically ```unittest```. It's another one of those "give a basic recommendation that people can evaluate once they have experience" issues.

We need to sort out getting the ```tests``` directory into the sdist. The ```MANIFEST.in``` has a stab at it, but I'm not sure it works. I raised a question about this on ```pypa-dev``` (in the long thread on this project) but didn't get a satisfactory answer...

**Comment by ncraike** [comment]
I would actually find a slightly more complex example of how tests should be structured to be useful (eg more than one test file).

I used the sampleproject as the base for my project, then read instructions in unittest and nose that all of my tests should "importable" for test discovery. I came back to sampleproject to see how that'd been accomplished with the tests in a separate directory from the other code, but it didn't demonstrate this.

I understand the desire to be framework-agnostic, but it'd be nice to have some demonstration of a scaleable way to write tests using one of the popular frameworks (whether it's unittest, nose, py.test). I don't know if all unittest/nose projects structure things differently to sampleproject so tests can be imported as, eg `myproject.tests`, or if they just use one of the special entry-point scripts which manipulate the `PYTHONPATH`, and I'd find it useful if _some_ sample project existed which showed a "recommended" setup.

**Comment by pfmoore** [comment]
@ncraike I don't think there is any common approach, unfortunately. With ```py.test``` (which is what I prefer these days) you don't even want the tests to be importable (and I think making them so is problematic).

So there really isn't anything we can do beyond having a ```tests``` directory before we get into making framework recommendations :-( (Actually, even having a ```tests``` directory is a decision - many projects seem to include tests within the distributed package itself).

**Comment by ncraike** [comment]
(Thanks for the quick reply.)

Ah, right. Yeah, I was trying to get a sense of what is done outside of the couple of really big, old projects I've worked on. Even knowing there isn't an agreed upon standard is valuable.

I can certainly understand the argument for _not_ installing your test code along with the code your project needs to actually do its job. I've also seen others advocate keeping your unit tests _right next to_ the code they test, with the argument that everyone knows where they are, then.

Well, I guess I'll just pick something, and not so feel bad that it isn't "best practice".

**Comment by pfmoore** [comment]
I know that feeling completely :-) These days, I tend to use py.test and just base what I do on pip's setup (which is very complex, but the basics are straightforward enough) just because it's what I'm most familiar with. I suspect that's a common approach.

BTW, I'm going to close this issue, as we're not likely to do anything with it, so no point in it just sitting here.
