### ISSUE TITLE
add .pypirc file

### ISSUE THREAD

**Issue by nueverest** [pypa/sampleproject#41]
It would be nice to see this file here as I ran into some snags.  So have others: http://stackoverflow.com/questions/21823705/how-to-fix-the-issue-pypi-test-not-found-in-pypic-when-submit-package-to-pypi

**Comment by pfmoore** [comment]
But that file sits in your home directory, not in the project directory. So it's not really appropriate for a sample project.

**Comment by nueverest** [comment]
Right. It also looks like `twine` is a better way to go then storing login info in plain text files.
