### ISSUE TITLE
Move main out of __init__

### ISSUE THREAD

**Issue by dmtucker** [pypa/sampleproject#65]
It'd probably be better to encourage people to keep `__init__.py` minimal.

**Comment by seancmonahan** [comment]
Move it into` __main__.py` per https://docs.python.org/3/library/__main__.html?

**Comment by seancmonahan** [comment]
Pull request https://github.com/pypa/sampleproject/pull/67

**Comment by pfmoore** [comment]
I think this is a matter of project choice. I don't think there's a particular best practice consensus here. So I'm inclined to keep things as they are as it's the simplest option.

Also, I don't like needing to import from `__main__` if I want access to the `main()` function - the double underscores indicate that it's not something that we should normally be importing from.

The `main()` function is often needed, for testing or for programmatic access to an application (if the app supports it). Importing that either from the package directory or from a `cli` submodule seems natural to me - importing it as

```python
    import foo.__main__

    foo.__main__.main([my, arguments, to, supply])
```

feels clumsy (I wouldn't do `from foo.__main__ import main` as that would probably clash with my *own* `main` function).

**Comment by seancmonahan** [comment]
@dmtucker 

`__main__.py` still requires a `if __name__ == '__main__':` check because any setuptools-created executables will have a different `__name__` such as `sample.__main__`. Btw, sorry the discussion has ended up in two places.

What do others think about just adding a `__main__.py`:

```
from . import main

if __name__ == '__main__':
    main()
```
?

As an aside, would a comment in `__init__.py` suggesting users consider moving their `def main():` elsewhere be useful?

**Comment by dmtucker** [comment]
I think mimicking `pip` should generally be fine...
Personally, I find the extra `if __name__` check redundant since `__main__.py` shouldn't be imported, but maybe that's just me. I would call trying to protect people who do weird things from themselves unpythonic.

[My response on the PR](https://github.com/pypa/sampleproject/pull/67#discussion_r180226813) is relevant too.
