### ISSUE TITLE
Help please: my first python package

### ISSUE THREAD

**Issue by oualib** [pypa/sampleproject#73]
Hi everyone,

I recently released a new Python Library (check here https://github.com/vertica/Vertica-ML-Python)
I followed the tutorial to allow PIP install and created the setup.py (I don't know if it is right)
I have inside the github page a folder named vertica_ml_python. I want that in the execution of 
pip install vertica_ml_python it goes to https://github.com/vertica/Vertica-ML-Python and copy paste the folder in the user site-packages folder (and that is all)
If someone can help me I would be really grateful.

Best,

Badr

**Comment by di** [comment]
@oualib If I'm understanding correctly, you might be interested in using pip's [VCS support](https://pip.pypa.io/en/stable/reference/pip_install/#git) instead in order to install directly from GitHub, it generally wouldn't be idiomatic to do what I think you're asking for.

**Comment by pradyunsg** [comment]
Let us know if you still have queries @oualib! :)
