### ISSUE TITLE
how is this project connected to kafka rest client?

### ISSUE THREAD

**Issue by Jianyi-Ren** [pypa/sampleproject#75]
the **Project link** - homepage 
for the project ['kafka-rest-client 0.8.0'](https://pypi.org/project/kafka-rest-client/)
leads towards this repo

Not sure how this project is connected to kafka. Was that a typo?

**Comment by di** [comment]
This project is not related, the author of that project forgot to update the homepage link when they forked this repo to start that package. You should reach out to them via email and let them know.

**Comment by Jianyi-Ren** [comment]
did so. thx
