### ISSUE TITLE
Wrong comment on keywords?

### ISSUE THREAD

**Issue by akitada** [pypa/sampleproject#78]
According to [Distutils' doc](https://docs.python.org/3/distutils/setupscript.html), `keywords` can be a list (preferred) or string. But the comment in [sampleproject's `setup.py`](https://github.com/pypa/sampleproject/blob/129382f0e90ce7f099ba1e9a8e6f6b1e76db0162/setup.py#L119) says it must be a string.

**Comment by di** [comment]
Technically [according to the specification for this field](https://packaging.python.org/specifications/core-metadata/#keywords) it can only be a string. Distutils is being friendly by converting a list into a string for the metadata file, but it really should be a string.

**Comment by akitada** [comment]
Thank you for the clarification. If that's the case I think distutils' doc should be updated because it explicitly states it must be a list.

**Comment by di** [comment]
Huh, TIL:

> _Changed in version 3.7_: setup now raises a TypeError if classifiers, keywords and platforms fields are not specified as a list.

**Comment by di** [comment]
I opened a general issue to address this ambiguity: https://github.com/pypa/packaging-problems/issues/186
