### ISSUE TITLE
Add a pyproject.toml

### ISSUE THREAD

**Issue by pfmoore** [pypa/sampleproject#79]
As an indication of best practice, we should consider adding a `pyproject.toml` file.

**Comment by pradyunsg** [comment]
SGTM. I'll make a PR tonight positively.

**Comment by Nazime** [comment]
The ``pyproject.toml`` is still not in the sample, is it best practice to put it in a project?

**Comment by dmtucker** [comment]
>  is it best practice to put it in a project?

Yes
