### ISSUE TITLE
Travis doesn’t run on pull requests

### ISSUE THREAD

**Issue by marcelm** [pypa/sampleproject#88]
I noticed that my PR #87 didn’t get tested on Travis. Apparently, the last PR to be tested was #71 and then #74 wasn’t, so something happend between April 26 and June 5, 2018.

**Comment by di** [comment]
Hmm, looks like the repository got deactivated somehow. I've re-enabled it, and kicked off a build on master: https://travis-ci.org/pypa/sampleproject/builds/487029018

It's still passing, so I'm going to close this. Thanks for the report!
