### ISSUE TITLE
video streamer is not working (pyzmq)

### ISSUE THREAD

**Issue by Samjith888** [pypa/sampleproject#91]
I'm using pyzmq  [from here](https://github.com/zeromq/pyzmq), the following code working fine with single system(by using the same system ip or localhost).
when i tried to run the viewer file one system and another file in a different system then its didn't show anything.

Viewer.py
`
import cv2
import zmq
import base64
import numpy as np
context = zmq.Context()
footage_socket = context.socket(zmq.SUB)
footage_socket.bind('tcp://*:5555')
footage_socket.setsockopt_string(zmq.SUBSCRIBE, np.unicode(''))
while True:
    try:
        frame = footage_socket.recv_string()
        img = base64.b64decode(frame)
        npimg = np.fromstring(img, dtype=np.uint8)
        source = cv2.imdecode(npimg, 1)
        cv2.imshow("Live", source)
        cv2.waitKey(1)

    except KeyboardInterrupt:
        cv2.destroyAllWindows()
        break
`

Streamer.py

`import base64
import cv2
import zmq
import tkinter
from tkinter import *
master = Tk()
master.title("Video-c")
master.geometry('350x200')
userInput = StringVar()
ll = Label(master, text="IP Address:",  font=("Arial", 10))
ll.config(height=2, width=15)
ll.place(x=15, y=65, height=18)
e1 = Entry(master, textvariable=userInput,width=20, font=("Arial", 12))
def connect(userInput):
    IP=userInput.get()
    context = zmq.Context()
    footage_socket = context.socket(zmq.PUB)
    footage_socket.connect('tcp://'+IP+':5555')

    camera = cv2.VideoCapture(0)  # init the camera

    while True:
        try:
            grabbed, frame = camera.read()  # grab the current frame
            frame = cv2.resize(frame, (640, 480))  # resize the frame
            encoded, buffer = cv2.imencode('.jpg', frame)
            jpg_as_text = base64.b64encode(buffer)
            footage_socket.send(jpg_as_text)

        except KeyboardInterrupt:
            camera.release()
            cv2.destroyAllWindows()
            break

e1.bind('<Return>', (lambda event: connect(userInput)))
e1.place(x=120, y=60, height=25)
ss = Button(text='connect', anchor='center', font=30, width=18, height=3, bd=0, command=(lambda: connect(userInput)))
act_img = PhotoImage(file='e1.png')
ss.config(image=act_img)
ss.place(x=200, y=110, height=68, width=68)
master.mainloop()`

**Comment by pfmoore** [comment]
This appears to have been raised against the wrong project.
