### ISSUE TITLE
Publish this project on PyPI

### ISSUE THREAD

**Issue by di** [pypa/sampleproject#95]
It would be nice to automatically publish this project at https://pypi.org/project/sampleproject/ as it changes .

**Comment by pfmoore** [comment]
Why would this be useful? It's not `pip install`-able. (Well, I guess it is, but it's not exactly useful if you do...)

**Comment by di** [comment]
Generally, it would be useful to demonstrate cause/effect here: you write X and it shows up on PyPI like Y.

In addition though, it was already published by someone else, and so it was out of date. So a user looking to see how the various configurations of this project get represented when publishing to PyPI would be confused.

**Comment by pfmoore** [comment]
OK, seems fair.

**Comment by SaltyCatFish** [comment]
Can this issue be closed based on @di comments from May 28, 2019?

**Comment by di** [comment]
Ideally this would be auto-published on merge. I've updated the issue body.
